#!/usr/bin/env bash
# Generate a structured CHANGELOG.md from git history since the last tag.
# Usage: bash changelog.sh [--since <tag>] [--output <file>]
set -euo pipefail

OUTPUT="CHANGELOG.md"
SINCE_TAG=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --since) SINCE_TAG="$2"; shift 2 ;;
    --output) OUTPUT="$2"; shift 2 ;;
    *) echo "Unknown option: $1" >&2; exit 1 ;;
  esac
done

# Find the last tag if not provided
if [[ -z "$SINCE_TAG" ]]; then
  SINCE_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
fi

if [[ -z "$SINCE_TAG" ]]; then
  RANGE="HEAD"
  VERSION_HEADER="## [Unreleased]"
else
  RANGE="${SINCE_TAG}..HEAD"
  VERSION_HEADER="## [Unreleased] — since \`${SINCE_TAG}\`"
fi

DATE=$(date +%Y-%m-%d)

declare -a ADDED FIXED CHANGED REMOVED OTHER

categorize_commit() {
  local subject="$1"
  local lower
  lower=$(echo "$subject" | tr '[:upper:]' '[:lower:]')

  if   [[ "$lower" =~ ^feat|^add|^new ]];                        then ADDED+=("$subject")
  elif [[ "$lower" =~ ^fix|^bug|^patch|^hotfix ]];               then FIXED+=("$subject")
  elif [[ "$lower" =~ ^refactor|^perf|^style|^chore|^update|^change|^improve ]]; then CHANGED+=("$subject")
  elif [[ "$lower" =~ ^revert|^remove|^delete|^drop ]];          then REMOVED+=("$subject")
  else OTHER+=("$subject")
  fi
}

# Read commits
while IFS= read -r line; do
  [[ -z "$line" ]] && continue
  categorize_commit "$line"
done < <(git log "$RANGE" --oneline --no-merges --format="%s" 2>/dev/null)

# Build the output
{
  echo "# Changelog"
  echo ""
  echo "> Auto-generated by \`changelog.sh\` on ${DATE}"
  echo ""
  echo "---"
  echo ""
  echo "${VERSION_HEADER}"
  echo ""

  if [[ ${#ADDED[@]} -gt 0 ]]; then
    echo "### Added"
    for item in "${ADDED[@]}"; do echo "- ${item}"; done
    echo ""
  fi

  if [[ ${#FIXED[@]} -gt 0 ]]; then
    echo "### Fixed"
    for item in "${FIXED[@]}"; do echo "- ${item}"; done
    echo ""
  fi

  if [[ ${#CHANGED[@]} -gt 0 ]]; then
    echo "### Changed"
    for item in "${CHANGED[@]}"; do echo "- ${item}"; done
    echo ""
  fi

  if [[ ${#REMOVED[@]} -gt 0 ]]; then
    echo "### Removed"
    for item in "${REMOVED[@]}"; do echo "- ${item}"; done
    echo ""
  fi

  if [[ ${#OTHER[@]} -gt 0 ]]; then
    echo "### Other"
    for item in "${OTHER[@]}"; do echo "- ${item}"; done
    echo ""
  fi

  total=$((${#ADDED[@]} + ${#FIXED[@]} + ${#CHANGED[@]} + ${#REMOVED[@]} + ${#OTHER[@]}))
  if [[ $total -eq 0 ]]; then
    echo "_No commits found in range \`${RANGE}\`._"
    echo ""
  fi

} > "$OUTPUT"

echo "✅ CHANGELOG written to ${OUTPUT} (${total:-0} commits)"
